
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: AzureCLI@2
  displayName: Login to ACR
  inputs:
    azureSubscription: 'sp-azdevops'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr login --name zekecs'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sp-azdevops'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr build -t zek/app-sampe:{{.Run.ID}} -r zekecs $(Pipeline.Workspace)/app/'
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '$(Pipeline.Workspace)/app/Dockerfile'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'sp-azdevops'
    appName: 'zek'