
trigger:
- master

pool:
  vmImage: "windows-latest"

steps:
- checkout: self
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'az account list -o table'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ezequiel-mpn (7641de69-433f-4802-baaf-a4126c027420)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list -o table'
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '$(Pipeline.Workspace)/app/Dockerfile'
