
trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
- group: az-examples

stages:
  - stage: dev
    displayName: "Develop"
    jobs:
      - deployment: deployNodeApp
        displayName: "Deploy Node App"
        environment: "azdevops-examples"
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self

              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'sp-azdevops'
                  scriptType: 'batch'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az group list -o table'

              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: |
                    ls $(Agent.BuildDirectory)
                    ls $(Build.Repository.LocalPath)
              - task: DockerInstaller@0
                inputs:
                  dockerVersion: '17.09.0-ce'
              - task: Docker@2
                inputs:
                  command: 'buildAndPush'
                  Dockerfile: '$(Build.Repository.LocalPath)/app/Dockerfile'

