
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: dockerRegistryServiceConnection1
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'sp-azdevops'
    appName: 'zek'