
trigger:
- master

pool:
  vmImage: "ubuntu-latest"

variables:
- group: az-examples

stages:
  - stage: dev
    displayName: "Develop"
    jobs:
      - deployment: deployNodeApp
        displayName: "Deploy Node App"
        environment: "azdevops-examples"
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self

              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: 'ls $(Build.Repository.LocalPath)'

              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: |
                    ls $(Agent.BuildDirectory)
                    ls $(Build.Repository.LocalPath)
                  
              - task: Docker@2
                inputs:
                  command: 'buildAndPush'
                  Dockerfile: '$(Build.Repository.LocalPath)/app/Dockerfile'
