
trigger:
- master

pool:
  vmImage: "windows-latest"

steps:
- checkout: self
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'az account list -o table'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sp-azdevops'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list -o table'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      dir $(Agent.BuildDirectory)
      dir $(Build.Repository.LocalPath)
    
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '$(Pipeline.Workspace)/app/Dockerfile'
