
trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
- group: az-examples

stages:
  - stage: dev
    displayName: "Develop"
    jobs:
      - deployment: deployNodeApp
        displayName: "Deploy Node App"
        environment: "azdevops-examples"
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self

              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: |
                    ls $(Agent.BuildDirectory)
                    ls $(Build.Repository.LocalPath)

              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'sp-azdevops'
                  scriptType: 'batch'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az acr build -t app/node-example:{{.Run.ID}} -r zekecs $(Build.Repository.LocalPath)/app

              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'sp-azdevops'
                  scriptType: 'batch'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az acr build -t app/node-example:latest -r zekecs $(Build.Repository.LocalPath)/app